Dev/lua
leggedrobotics/open3d_slam pull request #51
Opened 2022-11-18 20:50 UTC by jelavice

2022-12-05 08:28 UTC, nubertj requested changes

2022-12-05 08:28 UTC, nubertj commented on open3d_slam_io/open3d_slam_lua_io/src/minimal_example.cpp
> +//  watch(param.saving_.isSaveAtMissionEnd_);
comments

2022-12-05 08:28 UTC, nubertj commented on open3d_slam_io/open3d_slam_yaml_io/include/open3d_slam_yaml_io/parameter_loaders.hpp
> +/*
maybe move to a "legacy" folder or so?

2022-12-05 08:29 UTC, nubertj commented
I think overall the new structure is cool. But before merging it should be cleaned up and maybe structured a bit more nicely. Also I could not compile it although installing lua 5.2. I added this information to the readme. Anything else required?

2022-12-05 09:04 UTC, nubertj commented
okay, now i could run it and it works :) good to merge after the cleanup.

2023-01-18 11:19 UTC, jelavice commented on open3d_slam/include/open3d_slam/Parameters.hpp
> +	int featureKnn_=100;
yes, I would put formatting in a separate PR

2023-01-18 11:20 UTC, jelavice commented on open3d_slam_io/lua_parameter_dictionary/src/example.cpp
> +  std::cout << "Has key some_double_shizzle: " << std::boolalpha << dict.HasKey("some_double_shizzle") << "\n";
This is a minimal exapmle just to run the dictionary
I thought it would be helpful to have something like this

2023-01-18 11:22 UTC, jelavice commented on open3d_slam_io/open3d_slam_yaml_io/include/open3d_slam_yaml_io/parameter_loaders.hpp
> +/*
legacy folder or just delete it?

2023-01-18 11:28 UTC, jelavice commented on open3d_slam_io/open3d_slam_lua_io/src/minimal_example.cpp
> +
just to show how to load parameters, but maybe it is redundant since this is already done in the mapping node. Should I remove it?

2023-01-18 13:54 UTC, nubertj commented on open3d_slam_io/lua_parameter_dictionary/src/example.cpp
> +  std::cout << "Has key some_double_shizzle: " << std::boolalpha << dict.HasKey("some_double_shizzle") << "\n";
yeah might be useful. Just thought regarding the double_shizzle ;)

2023-01-18 13:54 UTC, nubertj commented on open3d_slam_io/open3d_slam_lua_io/src/minimal_example.cpp
> +
i think both is fine. But sometimes less is more

2023-01-18 13:55 UTC, nubertj commented on open3d_slam_io/open3d_slam_yaml_io/include/open3d_slam_yaml_io/parameter_loaders.hpp
> +/*
also good :)

2023-01-19 13:41 UTC, nubertj approved these changes

2023-01-23 10:37 UTC, merged