Feature/colored dense maps
leggedrobotics/open3d_slam pull request #66
Opened 2023-05-11 19:47 UTC by nubertj

2023-05-15 13:32 UTC, jelavice requested changes
See my comments inline. Few points:
1. Specific is this code to anymal? would it run on other robots? is it general enough?
2. some readme with basec instruction would be really helpful. someone who didn't write the package will have a hard time understanding what is the purpose of this package and how to run it. If you have an image that would be good.
3. MInor: I find the folder structure a bit confusing. now we have open3d_ros folder and then inside open3d_slam_ros. the top folder sounds like it's some ros deps related to open3d only, maybe ros only was a bit less ambiguous. Or maybe ros_packages

2023-05-15 13:32 UTC, jelavice commented on open3d_slam/open3d_slam/src/Submap.cpp
> +  const std::string layer = "layer";
use the definition from line 22. just to limit the magic variables a bit.

2023-05-15 13:32 UTC, jelavice commented on open3d_slam/open3d_slam/src/Voxel.cpp
> +  return (c.array().all() > 0.0) && (c.array().all() <= 1.0);
what happens if something actually is black in color? Then you would just have a hole in your map, no?

2023-05-15 13:32 UTC, jelavice commented on open3d_slam/open3d_slam/src/helpers.cpp
>  bool isValidColor(const Eigen::Vector3d& c) {
we have a duplication of implementation. Implement one method in terms of the other.

2023-05-15 13:32 UTC, jelavice commented on open3d_utils/open3d_pc_colorizer/include/open3d_pc_colorizer/PointCloudColorizer.hpp
> +  bool checkDepthValidity(const double& Z, const int& u, const int& v, unsigned int id);
PRimitive types should probably be passed by value:
e.g. https://stackoverflow.com/questions/14013139/is-it-counter-productive-to-pass-primitive-types-by-reference

2023-05-15 13:32 UTC, jelavice commented on open3d_utils/open3d_pc_colorizer/test/empty_test.cpp
> +TEST(Placeholder, emptyTest) {  // NOLINT
Consider removing if nothing is used here

2023-05-22 10:21 UTC, nubertj commented on open3d_ros/open3d_pc_colorizer_ros/config/parameters.yaml
> +generate_overlaid_images:                       false
because it is ros code and it was the easiest... You think we should move it to lua?

2023-05-22 10:29 UTC, nubertj commented on open3d_ros/open3d_pc_colorizer_ros/src/open3d_pc_colorizer_ros/PointCloudColorizerRos.cpp
> +  for (size_t i = 0; i < 1; i++) {
good catch, will check

2023-06-21 20:41 UTC, closed without merging